### PR TITLE
[-] Fix: column "id_shop" in "cms_lang" not exist before 1.6.0.12

### PR DESCRIPTION
**Pull request by PrestaEdit**

### CODE REVIEW

**Comment by joseantgv** [comment]
This error has been caused because of this commit: https://github.com/PrestaShop/blockcms/pull/11

I think that this is not a good patch, indeed it should create new column if it does not exist.

**Comment by PrestaEdit** [comment]
No ! Column will be created with an upgrade of the PrestaShop Core version.

The module doesn't need to create it, but take it in consideration AND take in consideration that the column doesn't exist in older versions ;-)

**Comment by joseantgv** [comment]
Sorry, I didn't see the first part of your commit :unamused: 

I thought that you only removed this id_shop from query

**Comment by PrestaEdit** [comment]
Ah ! Right ! ;-)

Seems good for me, then ;-)

**Comment by jeromenadaud** [comment]
Hi, thank you for you contribution.

Best regards.

**Pull request merged**
